### ISSUE TITLE
Decide on website design

### ISSUE THREAD

**Issue by salahusama** [mai-youth/website-fe#11]
We might do this ourselves. I'll try get an update from the designer soon.

**Comment by mahmoudal99** [comment]
Any updates on the design?

**Comment by salahusama** [comment]
Not really. When I get back I'll ask and check. We'll meet to discuss some things and decide on our design if its not ready by the time we meet.

**Comment by HaashimB** [comment]
Websites for inspiration:
* https://www.hubspot.com/
* https://www.dagusa.com/
* https://www.helpscout.com/blog/

**Comment by salahusama** [comment]
Check [this design](https://www.figma.com/file/wWnr58VAa0pNRx5rcwBz4B/MAI-Youth-Homepage?node-id=0%3A1) out. I think we start implementing this as step one and improve on it later.

**Comment by salahusama** [comment]
#32 implements the design. We can close this.
