### ISSUE TITLE
Decide whether to use a UI library or not

### ISSUE THREAD

**Issue by salahusama** [mai-youth/website-fe#14]
We should decide on this soon. I prefer a more "flat" design if we will. On the top of my head, I think [ant design](https://ant.design/) or [semantic ui](https://react.semantic-ui.com/) may be good.

We'll need to consider how good their documentation is, how adaptable the libraries are, and ease of use of their components.

**Comment by HaashimB** [comment]
Its between 2:
* https://react.semantic-ui.com
* https://blueprintjs.com/docs/

**Comment by HaashimB** [comment]
Agreed on Semantic due to the variety of card options. Closing issue.
