### ISSUE TITLE
Add functionality to change the homepage image

### ISSUE THREAD

**Issue by HaashimB** [mai-youth/website-fe#21]
The homepage background image should be able to be changed by the website admin. 

In the Admin page there should be an option to upload a new image that will replace the current homepage background image.

**Comment by salahusama** [comment]
Hmmm. Interesting. I'm not sure about this. It adds complexity when we can just change the image in the assets folder and keep its name.

Would be much easier than implementing the functionality for the admin to upload an image, us storing it, and then fetching it on page load.

The admin page could be article related only for now, although. We already have an API for articles.
