### ISSUE TITLE
Define project structure

### ISSUE THREAD

**Issue by salahusama** [mai-youth/website-fe#5]
How does this look:
```
src
 \-- js
    \-- components
    \-- api
    \-- ...
 \-- css
 \-- test
```

We can also get rid of the `js` folder and move everything in it one level above it.

**Comment by salahusama** [comment]
@hashdoge and @mahmoudal99, what do you think?

**Comment by hashdoge** [comment]
For now this looks good to me, might need to separate the components into re-usable and full pages or something along those lines. I think leave it in the JS folder, looks cleaner.

**Comment by salahusama** [comment]
When I was working on it, the js folder looked bad. Imports would look like `../js/components/...`, which I don't think is necessary.
