### ISSUE TITLE
Save articles as draft without publishing them

### ISSUE THREAD

**Issue by salahusama** [mai-youth/website-fe#50]
This will be useful to save articles still in progress without having them on the main articles page publicly.

A Boolean value of published on each article is a good solution. We can just show the published articles on the main page.

**Comment by mahmoudal99** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/42293856/66713302-d116e680-eda0-11e9-8c83-633aac2a6994.png)

**Comment by mahmoudal99** [comment]
Logic for saving as draft let me know what you would change anything

**Comment by mahmoudal99** [comment]
I tried to think of how gmail does it if you try exit an email without pressing send it will ask you if you want to save it as a draft

**Comment by salahusama** [comment]
Good work. I think it might be better to simplify this a bit though. Keep in mind you have to update the BE to support this as well.

For example, something like this might be a good idea...

To publish an article:
1. Article editor open
2. Details entered
3. Save and Publish clicked

To save an article as draft:
1. Article editor open
2. Details entered
3. Save clicked

You'll also need to see _(and toggle)_ whether the article is published or not. So we should be able to publish an article saved as draft and un-publish an article. A [toggle](https://react.semantic-ui.com/modules/checkbox/) in the admin table maybe?

**Comment by mahmoudal99** [comment]
Ive added a save button then i created a function which checks if the save button was clicked or the publish button then i added a save function in the article for modal.
I still need to add a function which saves the draft in the database
